name:
  maximum_length: 50
password:
  minimum_length: 6
  cancel_time: 2
email:
  maximum_length: 255
page:
  per_page: 6
size:
  gravatar: 80
  gravatar1: 30
  image: 5
remember:
  ischeck: "1"
image:
  maximum_length: 50
time:
  reset_expired: 2
  reset_expired1: 3
content:
  maximum_length: 140
per_page: 5
micropost:
  picture_accept: "image/jpeg,image/gif,image/png"

